### ISSUE TITLE
Can't find model file (resnet_imagenet.uff) in Huawei inference Latency

### ISSUE THREAD

**Issue by FullStackHan** [stanford-futuredata/dawn-bench-entries#123]
In [DAWNBench Inference Latency](https://dawn.cs.stanford.edu/benchmark/index.html#imagenet-inference-time), I saw Huawei got the first place (0.4945ms), which is great. So I want to try to use their code to reinference ImageNet on my T4. However, I can't find model file(resnet_imagenet.uff). @codyaustun 
@codeforfun9, could you please provide this file in your repo?  If so, I would be grateful.

Thanks

**Comment by codyaustun** [comment]
@FullStackHan it doesn't look like @codeforfun9 has responded. It might be worth emailing the address from the submission `dengbinbin1@huawei.com`.

I am going to close this issue for now, but please feel free to reopen if something changes or you find a resolution.
