### ISSUE TITLE
Kindly requesting some info

### ISSUE THREAD

**Issue by kirk86** [stanford-futuredata/dawn-bench-entries#15]
Hi everyone, thanks for this amazing work.
I was wondering if you could shed some light on the following questions.

I see different benchmarks on different dataset and different hardware but I am having some trouble inferring the following information:

For instance we see a difference by half at training time on TPUs but this between different models, i.e. resnet & amoeba-net.

I would like to know what speed gain if:

1. We have the same model on same hardware but different version of library, of instance TF 1.7 vs TF 1.8. In other words how much of that speed gain is solely based on the new software release

2. Test the same model on different hardware  but same version of library so that we can understand how much of the percentage gain is solely from the hardware.

Thanks in advance!

**Comment by frankchn** [comment]
I am a software engineer at Google Brain working on TensorFlow and TPUs and I can help shed some light about these questions:

(1) We are making continual improvements to TensorFlow and the TPU ecosystem and you can expect performance improvements when moving to TensorFlow 1.8 from 1.7. We will submit a updated ResNet-50 result with TensorFlow 1.8 later this week.

(2) We have included reproduction instructions with our submissions. While we don't have currently have the bandwidth to test on other hardware, we welcome the community to give it a go!
