### ISSUE TITLE
Can we exclude the accuracy computation from the inference time and preload the dataset into memory?

### ISSUE THREAD

**Issue by jgong5** [stanford-futuredata/dawn-bench-entries#32]

**Comment by codyaustun** [comment]
For inference time and cost submissions, yes, you can exclude the accuracy computation and preload the dataset into memory.

**Comment by jgong5** [comment]
Thanks. Our previous submission included both dataset loading and accuracy computation. Can we amend the result after  the submission deadline?

**Comment by codyaustun** [comment]
Changes after the deadline will be handled on a case by case basis given the circumstances and magnitude of the situation. I can't guarantee that it will be allowed. For reference, what submission are you referring to?

**Comment by jgong5** [comment]
@codyaustun Thanks. I was referring to all the ImageNet inference related submissions from Intel.
