### ISSUE TITLE
Printing # of epochs and training time during training

### ISSUE THREAD

**Issue by vilmara** [stanford-futuredata/dawn-bench-entries#47]
Hi, @yaroslavvb 

What script and flags are you using to get the training results with Resnet50-Imagenet?. I am running the benchmarks tf_cnn_benchmarks.py with Imagenet, and I need to print the epochs and training time during the training. I don't find the flags to activate the printing of this information, or do I need to modify the script to do it?

Here is the display I am getting:
Step Img/sec total_loss top_1_accuracy top_5_accuracy
1 images/sec: 451.0 +/- 0.0 (jitter = 0.0) 8.168 0.003 0.005

**Comment by ppwwyyxx** [comment]
https://github.com/stanford-futuredata/dawn-bench-entries/blob/master/ImageNet/train/diux_resnet50_p3-tensorpack.json

**Comment by codyaustun** [comment]
@vilmara, looks like @ppwwyyxx resolved this. Feel free to reopen if you had more questions.
