### ISSUE TITLE
AmoebaNet does not use the full validation set

### ISSUE THREAD

**Issue by ddkang** [stanford-futuredata/dawn-bench-entries#49]
@bignamehyp as per the other thread, setting "eval_batch_size=1024" is incorrect, as it will skip parts of the validation set. Could you rerun the validation checkpoints using a correct batch size and update the TSVs and json files?

**Comment by ddkang** [comment]
See here: https://github.com/stanford-futuredata/dawn-bench-entries/pull/48

**Comment by bignamehyp** [comment]
I'm on vacation util June 4th with limited Internet connectivity. Is there a deadline for this? I will try to squeeze some time to run the evaluation again.

**Comment by codyaustun** [comment]
@bignamehyp we don't have an explicit deadline, but we would like to resolve this in a timely manner. Can anyone else from your team re-evaluate your submissions?

**Comment by bignamehyp** [comment]
I will start rerun the evaluation with eval_batch_size=1000 and update the accuracies soon.

**Comment by bignamehyp** [comment]
@ddkang @codyaustun please take a look. Thanks

**Comment by ddkang** [comment]
Great, thanks. The updated TSVs look good, but can you also update the JSON files to use eval_batch_size=1000?

**Comment by bignamehyp** [comment]
Done

**Comment by codyaustun** [comment]
Thanks!
