### ISSUE TITLE
How to get the time for SQuAD training?

### ISSUE THREAD

**Issue by inspurasc** [stanford-futuredata/dawn-bench-entries#74]
@Deepak Narayanan

I can run through the code https://github.com/stanford-futuredata/dawn-bench-models/tree/master/tensorflow/SQuAD  with the command: CUDA_VISIBLE_DEVICES=3,4 python -m basic.cli --mode train --noload --len_opt --cluster

But I don't know how to get the time results, such as https://github.com/stanford-futuredata/dawn-bench-entries/blob/master/SQuAD/train/dawn_bidaf_1p100-dawn_tensorflow.tsv  
How the get the times for run one epoch?

**Comment by codyaustun** [comment]
@kelayamatoz can you handle this?

**Comment by kelayamatoz** [comment]
I think the easiest way would be to set the epoch number to run the same command with flag ```--num_epochs 1```. This would run training for 1 epoch and save a TensorFlow event file. You can use tensorboard to investigate the event file and get the training time for 1 epoch.

Regarding the tsv file, by looking at the commit it seems that @deepakn94 generated this record. I'm not sure how he got it though.

**Comment by deepakn94** [comment]
I believe I downloaded the file from Tensorboard, and then wrote some code to get it into the required format.

**Comment by codyaustun** [comment]
@inspurasc I haven't seen any activity on this issue in a month, so I am assuming it is resolved. Feel free to reopen if you are still having issues.
