### ISSUE TITLE
where to add repro instructions?

### ISSUE THREAD

**Issue by yaroslavvb** [stanford-futuredata/dawn-bench-entries#8]
I have reproduction instructions for the resnet50 as a google doc, where should I reference it?
https://docs.google.com/document/d/1I6sjUpU1myzQGqcX3NyezSkChVZIui8Gxo5vove9ZV0/edit#heading=h.gmrlbtx6xbvi

**Comment by codyaustun** [comment]
@yaroslavvb I would add it to the code in the codeURL from your submission or add an additional field under 'misc'. 'misc' is a catch all for any other useful information not specified in the original JSON examples.
