### ISSUE TITLE
Question on inference cost

### ISSUE THREAD

**Issue by yao-matrix** [stanford-futuredata/dawn-bench-entries#80]
Hi, 
To calculate the inference cost, is it permitted to use dual-instances in one VM? 
To say it explicitly:
1. Launch 2 inference processes(or threads), each serving 25k images in imagenet-2012-val
2. Get the total time and calculate the average cost for every 10k images.
The formula just like: max[sum(process1_time), sum(process2_time)] / 50 * 10 * vm_cost_per_milliseconds. 

For inference latency, we will still use: [sum(process1_time) + sum(process2_time)] / total_images to measure per image latency.

Thx very much.

**Comment by codyaustun** [comment]
1. Yes, you can have 2 inference process (or threads) running separately for instance cost assuming they are included in the cost of the machine. 
2. Your calculation seems correct, but what we require in the JSON file is the cost per image (i.e., the `cost` field), which we multiply by 10,000 before being displayed on the website.

For inference latency, your calculation seems correct, but make sure each process is using a batch size of one.
