### ISSUE TITLE
Clarification about training time for Imagenet 

### ISSUE THREAD

**Issue by sb2nov** [stanford-futuredata/dawn-bench-entries#9]
I had a quick question. In measuring the training cost and time should the job be run as:

1. Series of train and eval steps (1 epoch at a time) and then the total time is measured for both the train and eval combined.
OR
2. Do the training and store checkpoints at each epoch. This is the training cost. 
Eval results can be generated posthoc from the checkpoints but don't contribute to the training time. 

What are the guidelines on how should the job be configured here?

**Comment by codyaustun** [comment]
Option 2. You don't need to include eval time or the time to store checkpoints.
