### ISSUE TITLE
Will the DawnBench ImageNet inference match still be played?

### ISSUE THREAD

**Issue by ningluninglu** [stanford-futuredata/dawn-bench-entries#91]
Will the DawnBench ImageNet inference match still be played?  So far,  Only Huawei,  Alibaba,  Intel, three companies have been submitted. Thanks.

**Comment by codyaustun** [comment]
While we are still accepting rolling submissions, we welcome more entries to ImageNet inference.

**Comment by lvniqi** [comment]
Hi~ As mentioned in [this blog](https://dawn.cs.stanford.edu/2020/01/13/end_dawnbench_rolling/), we can't submit new scores in the future?

**Comment by codyaustun** [comment]
Great question! No, we will no longer accept updated scores. However, I will review pull requests if you need to update metadata like adding a link to the submission's source code.
